# Generated by Django 3.1.5 on 2021-03-21 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_name', models.CharField(max_length=250, verbose_name='Sura nomi')),
                ('audio_img', models.ImageField(upload_to='Audio_files/')),
                ('audio_files', models.FileField(upload_to='', verbose_name='Audioni yuklash')),
            ],
            options={
                'verbose_name': 'Audio',
                'verbose_name_plural': 'Audiolar',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Maqola nomi')),
                ('body', models.TextField(verbose_name='Matni')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='*')),
                ('author', models.CharField(blank=True, default='Admin', max_length=200, verbose_name='Muallif')),
                ('date', models.DateField(auto_now_add=True, verbose_name="Qo'shilgan vaqati")),
                ('image', models.ImageField(upload_to='Maqolalar_rasmi/', verbose_name='Maqola rasmi')),
            ],
            options={
                'verbose_name': 'Maqola',
                'verbose_name_plural': 'Maqolalar',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Ismi')),
                ('email', models.EmailField(max_length=250, verbose_name='Email')),
                ('subject', models.CharField(max_length=250, verbose_name='Mavzusi')),
                ('message', models.TextField(verbose_name='Xabar')),
            ],
            options={
                'verbose_name': 'Muhokama',
                'verbose_name_plural': 'Muhokamalar',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Imomi Azazm Rahmutullohi alayh jome masjid', max_length=200, verbose_name='Rasim matni')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Joylangan vaqti')),
                ('images', models.ImageField(upload_to='Gallerys/', verbose_name='Rasmi')),
            ],
            options={
                'verbose_name': 'Rasim',
                'verbose_name_plural': 'Rasimlar',
            },
        ),
        migrations.CreateModel(
            name='Namaz_time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Namoz nomi')),
                ('time', models.CharField(max_length=100, verbose_name='Namoz vaqti')),
            ],
            options={
                'verbose_name': 'Namoz vaqti',
                'verbose_name_plural': 'Namoz vaqtlari',
            },
        ),
        migrations.CreateModel(
            name='Sheikhs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='*')),
                ('name', models.CharField(max_length=200, verbose_name='Ismi')),
                ('direction', models.CharField(max_length=200, verbose_name="Yo'nalishi")),
                ('fullname', models.CharField(max_length=300, verbose_name='Toliq ismi')),
                ('surname', models.CharField(max_length=300, verbose_name='familiyasi')),
                ('address', models.CharField(max_length=500, verbose_name='Yashash manzili')),
                ('phone', models.CharField(max_length=100, verbose_name='Telfon raqami')),
                ('about', models.TextField(verbose_name="To'liq malumoti")),
                ('image', models.ImageField(upload_to='Sheikhs/', verbose_name='Rasmi')),
            ],
            options={
                'verbose_name': 'Qori va Imom',
                'verbose_name_plural': 'Qorilar va Imomlar',
            },
        ),
    ]
