# Generated by Django 3.2.4 on 2021-07-24 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_comment_blog_page'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'Rasim', 'verbose_name_plural': 'Rasmlar'},
        ),
        migrations.AlterField(
            model_name='gallery',
            name='title',
            field=models.CharField(default='Imomi Azazm Rahmutullohi alayh jome masjid', max_length=200, verbose_name='Rasm matni'),
        ),
    ]
